### PR TITLE
Upgrade to expressive 3

### PR DESCRIPTION
**Pull request by mateuszsip**
Implements #50 

Hi!

I still need to debug failing tests (works fine on local imo) and do some cleanup, but basically this is it.

I don't know expressive well, could you take a look?

Thanks!

### CODE REVIEW

**Comment by codeliner** [comment]
Thx @kejwmen Changes look good :+1: Do you want to add anything to the PR? Otherwise I'd merge it.

**Comment by kejwmen** [comment]
I still want to check why e2e test [fails](https://travis-ci.org/kejwmen/php-ddd-cargo-sample/jobs/447513267#L958) and fix it before merging.

**Comment by codeliner** [comment]
and green! great job :clap:

**Comment by kejwmen** [comment]
Updated chromedriver helped, LGTM!

**Comment by mateuszsip** [comment]
that was fast, thanks!

**Pull request merged**
